[package]
name = "txmodems"
publish = false
readme = "README.md"
repository = "https://github.com/shymega/txmodems"
description = "Rust library for Various MODEM file transfer protocols"
categories = ["rust", "data-transfer", "MODEM", "file-transfer"]
keywords = ["rust", "data-transfer", "MODEM", "file-transfer"]
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
license = "MIT"
edition = "2021"

[features]
default = []
# TODO: YMODEM/ZMODEM.
xmodem = []

[dependencies]
core2 = { version = "0.4.0", default-features = false }
log = "0.4.14"
crc16 = "0.4.0"
